version: "3.9"

services:
  workshopbot-service:
    build:
      context: .
    container_name: workshopbot-service


    expose:
      - "${INTERNAL_PORT:-8000}"
    environment:
      DOMAIN: ${DOMAIN}
      STACK: ${STACK}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_DSN: ${DB_DSN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${STACK}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${STACK}.entrypoints=websecure
      - traefik.http.routers.${STACK}.tls.certresolver=le
      - traefik.http.services.${STACK}.loadbalancer.server.port=${INTERNAL_PORT:-8000}
    networks:
      - proxy

  giphy-service:
    build:
      context: ./giphy_service
      dockerfile: Dockerfile
    container_name: giphy-service

    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  proxy:
    external: true